name: Configure AWS Credentials

on: 
  push:
    branches:
      - main

jobs:
  configure-aws-credentials:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::124355646724:role/t_rodman
          
      - name: Log AWS Credentials
        run: |
          aws sts get-caller-identity
          aws --region us-west-2 ssm get-parameter --with-decryption --name trust-her
          aws --region us-west-2 ssm get-parameter --with-decryption --name trust-him
          aws --region us-west-2 ssm get-parameter --with-decryption --name trust-me
          aws --region us-west-2 ssm get-parameter --with-decryption --name trust-them

